version: '3'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restdemo
      - MYSQL_PASSWORD=root
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=restdemo
      - DATABASE_PORT=3306